WIP: Geolocation implementations #5
trucidare/MauiBundler pull request #6
Opened 2023-07-02 09:45 UTC by trucidare

2023-07-02 16:25 UTC, PPetau requested changes
Looks fine. Just some files that should not end up in the repository

2023-07-02 16:25 UTC, PPetau commented on .vscode/settings.json
>  {
Can we ignore the configuration from the dotnet extension?

2023-07-02 16:25 UTC, PPetau commented on MauiBundler/Plugins/Plugin.Geolocation/wwwroot/Geolocation.cs.js
> +var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
This should not be included

2023-07-08 12:14 UTC, trucidare commented on .vscode/settings.json
>  {
Yes - removed now

2023-07-08 21:29 UTC, PPetau commented on MauiBundler/Plugins/Plugin.Geolocation/Geolocation.cs.ts
> +export class GeoPosition {
This should be an Interface only

2023-07-09 12:37 UTC, trucidare commented on MauiBundler/Plugins/Plugin.Geolocation/Geolocation.cs.ts
> +export class GeoPosition {
Done

2023-07-09 14:01 UTC, PPetau commented on MauiBundler/Plugins/Plugin.Geolocation/Services/GeolocationService.android.cs
> +        await jsRuntime.InprocessJSRuntime!.InvokeVoidAsync($"MauiBundler.Plugins.{nameof(GeoLocation)}.statusChanged", message);
This can be something we should handle internally by the Bundler

2023-07-09 14:02 UTC, PPetau approved these changes
LGTM

2023-07-09 16:11 UTC, merged